version: "3.9"

services:
  aggregator:
    build: .
    container_name: bandwidth-aggregator
    # Run the aggregator data-collector (not the FastAPI server)
    command: ["python", "-m", "src.aggregator"]
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  ping-monitor:
    build: .
    container_name: ping-monitor
    restart: unless-stopped
    command: ["python", "-m", "src.ping_monitor"]
    env_file:
      - .env
    volumes:
      - ./config.yaml:/app/config.yaml:ro
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  api:
    build: .
    container_name: reseller-api
    restart: unless-stopped
    command: ["python", "-m", "api.main"]
    env_file:
      - .env
    ports:
      - "8000:8000"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Optional InfluxDB for storing metrics (disabled by default)
  # Uncomment if you plan to write usage data to InfluxDB later
  # influxdb:
  #   image: influxdb:1.8
  #   container_name: influxdb
  #   restart: unless-stopped
  #   ports:
  #     - "8086:8086"
  #   environment:
  #     - INFLUXDB_DB=networking
  #     - INFLUXDB_ADMIN_USER=admin
  #     - INFLUXDB_ADMIN_PASSWORD=adminpassword
  #   volumes:
  #     - ./data/influxdb:/var/lib/influxdb 